language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - josleke@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: wWciqe2AN4wVdpNRD9JNBhHkUWadEAWvBP1N6BQxUQh0BadcUS/w24ZZZaohpyU2fMrZtHUlidZcgWa3WOnW1t+PquDnTOq0AofUSHWItKzcFhAd0eiIiEjro1Q1mZTaRY82zk/l0jNP99fkXn5CqFvg5vh2zqEPfTd80mA9XHOJKXpSiLN3ZaDXUiVgJGreIcbNwkxYIpL85E0m94X7eedw0lxkvEAPlMNo0aC41+yyGeWMGW0Z418628BWluu8IJVg2p47ScOYh+YaELMl+5RjCa8WsqpiMUsAwBcsjfCq91Q8AVxV/prJpHKQnKJtYi4I9d0uStKcZGxUMPI2XGvA0CoJYYoB5anzWD/hI6+xHCnaZR4x3YDY715JSvFq8HjC8qySi4qUQ2OtpZqApTxTlCbIKBaoislSk/RpjgWN4F7exicXsfGFhLrJF5MiIY8UzyYFv77YCRyqe/4uRwCc8myVFCvDyveVww12bcWijUfS/r1Rzhr5l4dX66/ptl+xdhDMFcNayevDY5UDLCk6fJExcAi8B07ezKZ1BCxt+IMMM3cX0vMA7HjIEDhkVGFIuECUJeN3h0qfFtkkWIWsxdT0ATsW/4ewZjCOqoXtc0LjvYJ+0CuWWXyOXE2s1h/TGLic5GMwFfiP//tpiFq05nNrUo7j0w/wMTQ1yys=
  - secure: A7nso7oD3bIGExJ977UPSLUBJrWK+dYb1Fr4vfuW+nze0nQ4nXdrV7212PKgOUY61LuUnV1NBmYcVGtb3UcSXd3WkbGVzFM0SycKjUFDGfAG9Q0KCK6fw/s4PbkMvdiyHSgoTrsM/KLydbqdrjBni8VdIHTqG+DHqCrKerbT4u8MTsKZ6vwAwCzl28IMwf/nujAmkSuJy6VZZZzdQcfKKAHTFc7bWpfO0atdUGPqAycz4TqCUb+zpIwPU1XMo5fQu6N2JwFyPyUp5neON97fzc4VkoyVpyW+ZONFMkNr9MFDZP3yuNqnEOyxDRczLy0opRIjI7/8zOM1on7XNpa8Ytd1W7qLvO3pPaGZtm/r3bN0O9pGg6BOA4DrRRJYcZGJy30yabGH+K/ExtkQfLxl9OYN8uDJ3vbyslrBNZXl5G4+8US+6vD3D2hiAbKMhaet22GkupcoYOHbbOlx42Awr2Jj48S6mmGoqgolYa/X/ZuBMU95/25Aja5+icSJlmD8UJ32U2qrKR79P1z3xlXgJPp+QICWvPpFRGTfH6L5BUGjIesVSSePOHbw+mjnkpaPLh2fqrDxeHUjEhYEWjSpUJoylJG+CcPPQqaSzAio/eFxsn7R8D8t+iTnpA+jOImOBZABhVx1QXhoWK1PVINkolG0BA1qXc2NoGLi0uZnjw0=
  - secure: WD4uHnly7S7fsm5E1N5KMXY1q/8nKmQZgV/715rjygIsDIZVzWUngYuJUZpbMf3HKJgoNl9nk32Ho4qcOSO6X0bSVaueq2vhGzNPUNqAvhiJOwiuXd25WL62cZAc7GklrVcR7pcs6vUQ0d18S/lRPvRvshlWWifmwMIhi1S4OD+LhXlMrRLRtiycEpHpdO0uUqiegYEJIGRzWjGFM1KHyfLFJKWgNFLMa/pyOJPn/rcdfVlPOqz6AI7LCqDr5MXroVDUiLR2F3siE+95snCto42fvMKORgkk1Rh4EdDxElqSFDf6F/FKAhG4rRbKx3BsjrUQkXUnzOER1zMdbSqXvfrWX5Wr0rFbW6oCmhr5ymCUZTTm4PC832mY68tnb1xv8Y6Q6o2fNaqB3mrByIKmAbCecY6If4GLYXXcsb37PGkgp+R706sd/MjWUKVblD1p4TeGvcHf7X2g02sgCWQH1Z20UBOXzpK1ZT/YTpm2VXPbnMRowyoO8X9FkfbNa3Ncl4katlrsuLzrS/A753CnWpTqvn2wxzeDrLzBdsMgnt1jKFXNa9+OzPOISReaUBdyTxndwgdeZAy/xP1+m9QS4Jp9OELNJcAE9kjlb1MfcZpTG4YaCZooaCGMNYsGIgfkKyECqtO5ClH3vYimVA03JTp5f1absk2yWmHSvI6Ub4I=
  - secure: anoSAl//1Dj+r9sO4oMNqo5uD9qk3cmy2mbQMGJsaB/jQB8vN1kaZAymM9u5ZeJ2pNJJsclnUHlzWl3cX870ncvN/8qMoUMM9PXQnBjFuHTns53/G1GOO4rT5U47XbgDfMv8+RlQBpmxpVkY6lEsBuZK0nPM0nat2/5rA+Ub6ya40o1oWvP8ceirv5CjL/Uz2PVRVoWfKvnL09Du7pkwHjsm80DSCo4wnmCnsCxrl6AWprNsdWd/Bir4d5lbdG4Lx6EsHIIWqQ+zwUCb+Cy+pkqBgrcyzqdR2nQvucDqHgKGT/C8sJt7teCczOLgQWsGr5D0VXGTvBCm3wpJRG86896uZE10Q6V2ojfw36ncvAq7NR2UAzdtQ0CpMRJDm3ia+Jdu7nXH+96JnKHNWgsfz5WtHsdsVcVh4pnlxgdfpcIhF/Moxt9LrxUF8MUw87wRhJDwRv+Ssm9qAQjAZfPKd80nfbWVibWcmHjTRgpZtWDrA2b11YUgQK9r9ysuleoC9VCpN+hUq1JvwkN40Xfq0+1KobzeKbDnYEXaqEk5uIHoL6hdGEcdWyB9gYd3B/Ai0hQZc/u6BC+I28VO60wijGKz8zFvIjIn1n2GR+v9q+axQFxl3lGhGQMiTAC3180FOYyxS5gXvNpOZuTrYtYpuLnMil9KY44WGKVshK6Obws=
  - secure: cLQXEpBVgYh4OM4eaJj4UT5gBQv/wtV5/jMI1zI5O3RrfuUmSYzrf5XEqgLXOmTBobKr7Hvsm+RFpWF/1RrRFiFm9DSr3nlaWPXd3Mme6O6dMMa2BUdeQgvzcKF7RhI1+u/f2py0uJVpWfoNkaWATexXUQTANNE1ySY+okvOBq4+YxhCr1YKdL6RU9GBK/W7T3J2PA062+tUekTzfshVASFMB4UmabkrNX6OXh1qDupigmN8X1RH5qFVkDZ95cSEhA1h9JihFqosvLQYc97oGHIpSZwWwF0Mm4nckSRYeyN07wc3maQ1nvD7IMIJdlFwv4OHEJFRlhT8RiziC/o7CH/CTKuKptEWeFHXTz0Bk6JK537BgJpWLeFAQD5/bwrt9eJt7XOcobFxaSeEMidgGhsMSYw25xcX5oXIQJGTY1T3RgT7s2HnGFEBH1tuxXXFHgUpaBJc1PQGaXP9ESbdgSs573AUqsXk9jaQgz4PR//bMTR+SrWgZLE+5AjSEtMmt/D1aqZbhkCMRGxHEG9fYBuSQP219Sh8YCxjRt1Sfzb6kI/Q3aRZunQ9WDSOIfSGEsF5kmlCyOph5nsqGVpo0Y8DujZSyU89cBSIutAmEZxVCFzCTC2qD1AorvFqa5McRIJLZI2RuHQP+Lpu4iNMwA8Z1VUf0D9dZscLsIO54BM=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=josleke-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=18.130.217.126
- export PLATFORM_TEST_NAME="josleke-ms-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
