server:
  port: 8282

logging:
  level:
    com.jade: DEBUG
    org.apache: INFO
    org.apache.tomcat.util: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8089/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    stream:
      bindings:
        output:
          destination:  orgChangeTopic
          content-type: application/json
        rabbit:
          binder:
            nodes: localhost
            brokers: localhost

