server:
  port: 8089
  context-path: /auth

jwt.signing.key: 345345fsdfsf5345
jwt.store.name: mservice

logging:
  level:
    org.apache: INFO
    org.apache.tomcat.util: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      filter-order: 3