#!/bin/sh
echo "********************************************************"
echo "Waiting for the eureka server to start on port $EUREKASERVER_PORT"
echo "********************************************************"
while ! `nc -z eurekaserver $EUREKASERVER_PORT`; do sleep 3; done
echo "******* Eureka Server has started - AuthService **********"

echo "********************************************************"
echo "Waiting for the Database server to start on port $DATABASE_PORT"
echo "********************************************************"
while ! `nc -z database $DATABASE_PORT`; do sleep 3; done
echo "******* Database Server has started - AuthService **********"

echo "********************************************************"
echo "Waiting for the configuration server to start on port $CONFIGSERVER_PORT"
echo "********************************************************"
while ! `nc -z configserver $CONFIGSERVER_PORT`; do sleep 3; done
echo "******* Configuration Server has started - AuthService **********"

#echo "********************************************************"
#echo "Waiting for the configuration server to start on port $CONFIGSERVER_PORT"
#echo "********************************************************"
#while ! `nc -z configserver $CONFIGSERVER_PORT`; do sleep 3; done
#echo "*******  Configuration Server has started"

#echo "********************************************************"
#echo "Waiting for the kafka server to start on port $KAFKASERVER_PORT"
#echo "********************************************************"
#while ! `nc -z kafkaserver $KAFKASERVER_PORT`; do sleep 10; done
#echo "******* Kafka Server has started"

#echo "********************************************************"
#echo "Waiting for the REDIS server to start  on port $REDIS_PORT"
#echo "********************************************************"
#while ! `nc -z redis $REDIS_PORT`; do sleep 10; done
#echo "******* REDIS has started"

#echo "********************************************************"
#echo "Waiting for the ZIPKIN server to start  on port $ZIPKIN_PORT"
#echo "********************************************************"
#while ! `nc -z zipkin $ZIPKIN_PORT`; do sleep 10; done
#echo "******* ZIPKIN has started"


echo "********************************************************"
echo "Starting OAuth Server with Configuration Service via Eureka"
echo "********************************************************"
java -Djava.security.egd=file:/dev/./urandom -Dserver.port=$SERVER_PORT   \
     -Deureka.client.serviceUrl.defaultZone=$EUREKASERVER_URI             \
     -Dspring.cloud.config.uri=$CONFIGSERVER_URI                          \
     -Dspring.profiles.active=$PROFILE -jar ./@project.build.finalName@.jar

#echo "********************************************************"
#echo "Starting License Server with Configuration Service via Eureka :  $EUREKASERVER_URI:$SERVER_PORT"
#echo "********************************************************"
#java -Djava.security.egd=file:/dev/./urandom -Dserver.port=$SERVER_PORT   \
#     -Dspring.profiles.active=$PROFILE -jar ./u@project.build.finalName@.jar
#


#     java -Djava.security.egd=file:/dev/./urandom -Dserver.port=$SERVER_PORT   \
#     -Deureka.client.serviceUrl.defaultZone=$EUREKASERVER_URI             \
#     -Dspring.cloud.config.uri=$CONFIGSERVER_URI                          \
#     -Dspring.cloud.stream.kafka.binder.zkNodes=$KAFKASERVER_URI          \
#     -Dspring.cloud.stream.kafka.binder.brokers=$ZKSERVER_URI             \
#     -Dspring.zipkin.baseUrl=$ZIPKIN_URI                                  \
#     -Dspring.profiles.active=$PROFILE -jar ./u@project.build.finalName@.jar